"""2nd migration

Revision ID: 70d130b9d7ed
Revises: 8e6a40b3dd83
Create Date: 2021-02-16 12:29:11.077917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d130b9d7ed'
down_revision = '8e6a40b3dd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_area_entry', sa.String(), nullable=True),
    sa.Column('problem_area_date', sa.DateTime(), nullable=True),
    sa.Column('user_id_fk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_entry', sa.String(), nullable=True),
    sa.Column('skill_date', sa.DateTime(), nullable=True),
    sa.Column('user_id_fk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('skills')
    op.drop_table('problem_area')
    # ### end Alembic commands ###
